version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: packages/app/Dockerfile
      args:
        NODE_ENV: production
    restart: always
    ports:
      - 8080:8080
