name: App - CI

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - master
  #     - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker build . --file packages/app/Dockerfile.test.dockerfile
