name: App - Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List workspace

      - name: Test
        run: |
          cd packages/app && pwd && ls -la
          docker build . --file Dockerfile.test.dockerfile
      - name: Build
        run: |
          cd packages/app && pwd && ls -la
          yarn install && yarn build:github && yarn config:generate:github
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
