name: UI - CI

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - master
  #     - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cd packages/ui && pwd && ls -la
          echo 'Hello, world!'
